### PR TITLE
83 pythonise fceqnannualsine

### PR DESCRIPTION
**Pull request by j-emberton**
Pythonised and added tests for fcEqnAnnualSine.

@dorchard , I don't think this is the implementation you had in mind but I couldn't get the test_engine to work. Could you suggest your proposed implementation?

Tests currently pass.

Update: Python engine implementation agreed in unifiedEngine branch. Merged and implemented here.

### CODE REVIEW

**Comment by dorchard** [comment]
I have fixed the testing now - I need to do some more work to handle the way we do some overloading in the MATLAB engine. I've pushed the changes here but will make the parallel changes in https://github.com/Cambridge-ICCS/ONEFlux/pull/64 too.

**Comment by j-emberton** [comment]
Hi @dorchard , I still don't have any luck with this. With your updated code, the python versions of the tests still don't run. I can demonstrate this by changing the python code so it should fail, but all tests that are run still pass.

The fundamental problem is that there is no communication between the test and the fixture to indicate what languages should be run. I have tried to fix this in my latest commit where I add a parameterisation to the test so that the test language is specified each time.

Despite this there is a further downstream issue where the `Python_Engine` fails to find and load the correct function. I have added code to point the engine to the storage location for the python modules but for some reason I'm unable to load the function properly. This results in the tests failing.

Would be grateful if you could take a look and tell me what you think. I have broken the engine for all tests outside of this specific function with these changes, but once we fix this it'll be trivial to get the tests working globally.

**Comment by j-emberton** [comment]
requires PR #64 to be merged into ustar_cp_refactor_main first
all tests pass

**Review by dorchard — APPROVED** [review]
Works well - all tests pass for python. Good documentation.

**Pull request merged**
