### PR TITLE
Testing + modularisation of cpdbootstrap

### PR DESCRIPTION
**Pull request by dorchard**
This PR merges the work on testing and modularsation (+ subsequent testing) for cpdBootstrapUStarTh4Season20100901.m
PRs have been separately reviewed on each part of this work. This PR brings the work into the main refactoring branch.

### CODE REVIEW

**Comment by dorchard** [comment]
I have double checked that all tests pass, so I think we can merge this into the central branch ustar_cp_refactor_main now. Okay @j-emberton @tztsai @isaacaka ?

**Comment by dorchard** [comment]
(then we can branch off `ustar_cp_refactor_main` for the next steps of the work.

**Comment by j-emberton** [comment]
yeah that works for me

**Comment by casterkay** [comment]
Yes works for me

**Comment by isaacaka** [comment]
Yes, looks good.

**Pull request merged**
